# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/mechO

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/mechO

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/mechO/CMakeFiles /home/pi/mechO/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/mechO/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mechO

# Build rule for target.
mechO: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mechO
.PHONY : mechO

# fast build rule for target.
mechO/fast:
	$(MAKE) -f CMakeFiles/mechO.dir/build.make CMakeFiles/mechO.dir/build
.PHONY : mechO/fast

src/list.o: src/list.c.o

.PHONY : src/list.o

# target to build an object file
src/list.c.o:
	$(MAKE) -f CMakeFiles/mechO.dir/build.make CMakeFiles/mechO.dir/src/list.c.o
.PHONY : src/list.c.o

src/list.i: src/list.c.i

.PHONY : src/list.i

# target to preprocess a source file
src/list.c.i:
	$(MAKE) -f CMakeFiles/mechO.dir/build.make CMakeFiles/mechO.dir/src/list.c.i
.PHONY : src/list.c.i

src/list.s: src/list.c.s

.PHONY : src/list.s

# target to generate assembly for a file
src/list.c.s:
	$(MAKE) -f CMakeFiles/mechO.dir/build.make CMakeFiles/mechO.dir/src/list.c.s
.PHONY : src/list.c.s

src/mechO.o: src/mechO.c.o

.PHONY : src/mechO.o

# target to build an object file
src/mechO.c.o:
	$(MAKE) -f CMakeFiles/mechO.dir/build.make CMakeFiles/mechO.dir/src/mechO.c.o
.PHONY : src/mechO.c.o

src/mechO.i: src/mechO.c.i

.PHONY : src/mechO.i

# target to preprocess a source file
src/mechO.c.i:
	$(MAKE) -f CMakeFiles/mechO.dir/build.make CMakeFiles/mechO.dir/src/mechO.c.i
.PHONY : src/mechO.c.i

src/mechO.s: src/mechO.c.s

.PHONY : src/mechO.s

# target to generate assembly for a file
src/mechO.c.s:
	$(MAKE) -f CMakeFiles/mechO.dir/build.make CMakeFiles/mechO.dir/src/mechO.c.s
.PHONY : src/mechO.c.s

src/parser.o: src/parser.c.o

.PHONY : src/parser.o

# target to build an object file
src/parser.c.o:
	$(MAKE) -f CMakeFiles/mechO.dir/build.make CMakeFiles/mechO.dir/src/parser.c.o
.PHONY : src/parser.c.o

src/parser.i: src/parser.c.i

.PHONY : src/parser.i

# target to preprocess a source file
src/parser.c.i:
	$(MAKE) -f CMakeFiles/mechO.dir/build.make CMakeFiles/mechO.dir/src/parser.c.i
.PHONY : src/parser.c.i

src/parser.s: src/parser.c.s

.PHONY : src/parser.s

# target to generate assembly for a file
src/parser.c.s:
	$(MAKE) -f CMakeFiles/mechO.dir/build.make CMakeFiles/mechO.dir/src/parser.c.s
.PHONY : src/parser.c.s

src/pitchvals.o: src/pitchvals.c.o

.PHONY : src/pitchvals.o

# target to build an object file
src/pitchvals.c.o:
	$(MAKE) -f CMakeFiles/mechO.dir/build.make CMakeFiles/mechO.dir/src/pitchvals.c.o
.PHONY : src/pitchvals.c.o

src/pitchvals.i: src/pitchvals.c.i

.PHONY : src/pitchvals.i

# target to preprocess a source file
src/pitchvals.c.i:
	$(MAKE) -f CMakeFiles/mechO.dir/build.make CMakeFiles/mechO.dir/src/pitchvals.c.i
.PHONY : src/pitchvals.c.i

src/pitchvals.s: src/pitchvals.c.s

.PHONY : src/pitchvals.s

# target to generate assembly for a file
src/pitchvals.c.s:
	$(MAKE) -f CMakeFiles/mechO.dir/build.make CMakeFiles/mechO.dir/src/pitchvals.c.s
.PHONY : src/pitchvals.c.s

src/queue.o: src/queue.c.o

.PHONY : src/queue.o

# target to build an object file
src/queue.c.o:
	$(MAKE) -f CMakeFiles/mechO.dir/build.make CMakeFiles/mechO.dir/src/queue.c.o
.PHONY : src/queue.c.o

src/queue.i: src/queue.c.i

.PHONY : src/queue.i

# target to preprocess a source file
src/queue.c.i:
	$(MAKE) -f CMakeFiles/mechO.dir/build.make CMakeFiles/mechO.dir/src/queue.c.i
.PHONY : src/queue.c.i

src/queue.s: src/queue.c.s

.PHONY : src/queue.s

# target to generate assembly for a file
src/queue.c.s:
	$(MAKE) -f CMakeFiles/mechO.dir/build.make CMakeFiles/mechO.dir/src/queue.c.s
.PHONY : src/queue.c.s

src/sequence.o: src/sequence.c.o

.PHONY : src/sequence.o

# target to build an object file
src/sequence.c.o:
	$(MAKE) -f CMakeFiles/mechO.dir/build.make CMakeFiles/mechO.dir/src/sequence.c.o
.PHONY : src/sequence.c.o

src/sequence.i: src/sequence.c.i

.PHONY : src/sequence.i

# target to preprocess a source file
src/sequence.c.i:
	$(MAKE) -f CMakeFiles/mechO.dir/build.make CMakeFiles/mechO.dir/src/sequence.c.i
.PHONY : src/sequence.c.i

src/sequence.s: src/sequence.c.s

.PHONY : src/sequence.s

# target to generate assembly for a file
src/sequence.c.s:
	$(MAKE) -f CMakeFiles/mechO.dir/build.make CMakeFiles/mechO.dir/src/sequence.c.s
.PHONY : src/sequence.c.s

src/stepper.o: src/stepper.c.o

.PHONY : src/stepper.o

# target to build an object file
src/stepper.c.o:
	$(MAKE) -f CMakeFiles/mechO.dir/build.make CMakeFiles/mechO.dir/src/stepper.c.o
.PHONY : src/stepper.c.o

src/stepper.i: src/stepper.c.i

.PHONY : src/stepper.i

# target to preprocess a source file
src/stepper.c.i:
	$(MAKE) -f CMakeFiles/mechO.dir/build.make CMakeFiles/mechO.dir/src/stepper.c.i
.PHONY : src/stepper.c.i

src/stepper.s: src/stepper.c.s

.PHONY : src/stepper.s

# target to generate assembly for a file
src/stepper.c.s:
	$(MAKE) -f CMakeFiles/mechO.dir/build.make CMakeFiles/mechO.dir/src/stepper.c.s
.PHONY : src/stepper.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... mechO"
	@echo "... src/list.o"
	@echo "... src/list.i"
	@echo "... src/list.s"
	@echo "... src/mechO.o"
	@echo "... src/mechO.i"
	@echo "... src/mechO.s"
	@echo "... src/parser.o"
	@echo "... src/parser.i"
	@echo "... src/parser.s"
	@echo "... src/pitchvals.o"
	@echo "... src/pitchvals.i"
	@echo "... src/pitchvals.s"
	@echo "... src/queue.o"
	@echo "... src/queue.i"
	@echo "... src/queue.s"
	@echo "... src/sequence.o"
	@echo "... src/sequence.i"
	@echo "... src/sequence.s"
	@echo "... src/stepper.o"
	@echo "... src/stepper.i"
	@echo "... src/stepper.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

